model:
  base_learning_rate: 1e-4
  target: unidemoire.models.moire_nets.Demoireing_Model  # ldm.models.autoencoder.AutoencoderKL
  params:
    model_name: ESDNet
    mode: COMBINE_ONLINE    # COMBINE_ONLINE, COMBINE_ONLINE_ONLY, original
    blending_method: unidemoire     # unidemoire, shooting, moirespace, undem 
    blending_model_path: ./models/moire_blending/bl_fhdmi.ckpt
    dataset: TIP
    evaluation_time: False
    evaluation_metric: True
    save_img: True
    network_config:
      # ESDNet
      en_feature_num: 48
      en_inter_num: 32
      de_feature_num: 64
      de_inter_num: 32
      sam_number: 2       # ESDNet:1, ESDNet-L:2
    
      # MBCNN
      n_filters: 64
    
    loss_config:
      # ESDNet
      LAM: 1
      LAM_P: 1

    optimizer_config:
      # ESDNet
      beta1: 0.9
      beta2: 0.999
      T_0: 50                   # The total epochs for the first learning cycle (learning rate warms up then)
      T_mult: 1                 # The learning cycle would be (T_0, T_0*T_MULT, T_0*T_MULT^2, T_0*T_MULT^3, ...)
      eta_min: 0.000001

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    wrap: True
    train:
      target: unidemoire.data.moire_blend.moire_blending_datasets
      params: 
        args:
          natural_dataset_name: FHDMi
          uhdm_dataset_path: /inspurfs/group/mayuexin/yangzemin/data/uhdm_data/train
          fhdmi_dataset_path: /inspurfs/group/mayuexin/yangzemin/data/fhdmi_data/train
          tip_dataset_path: /inspurfs/group/mayuexin/yangzemin/data/tip2018/train
          moire_pattern_path: /inspurfs/group/mayuexin/yangzemin/data/generated/fake_ready5
          loader: crop
          crop_size: 384
        paired: True  # 是否用 paired 的 real-moire
        mode: train
    
    # test:   # UHDM 测试集
    #   target: demoire.data.uhdm.uhdm_datasets
    #   params:
    #     args:
    #       dataset_path: /inspurfs/group/mayuexin/yangzemin/data/uhdm_data/test
    #       LOADER: default
    #     mode: test

    # test:   # FHDMi 测试集
    #   target: demoire.data.fhdmi.fhdmi_datasets
    #   params:
    #     args:
    #       dataset_path: /inspurfs/group/mayuexin/yangzemin/data/fhdmi_data/test
    #       LOADER: default
    #     mode: test       

    test:   # TIP 测试集
      target: demoire.data.tip.tip_datasets
      params:
        args:
          dataset_path: /inspurfs/group/mayuexin/yangzemin/data/tip2018/test
          LOADER: default
        mode: test      

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        increase_log_steps: False
        rescale: False  # 去摩尔模型没有将数据从[0,1]转化到[-1, 1]!
        batch_frequency: 500   # 每隔多少步调用一次 ImageLogger 来保存训练时的图片
        max_images: 8

  trainer:
    benchmark: True
    # accumulate_grad_batches: 1
    max_epochs: 150     # 训练总 Epoch 数，练完之后自动开始 testing